name: "gitleaks"

on:
  push:
    branches: 
      - Master
      - staging
  pull_request:
    branches: [ Master ]


jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
