name: build docker and push

on:
  push:
    branches:
      - 'Master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bt66/web-example-golang:latest

name: remote ssh command
on:
  push:
    branches:
      - 'Master'

jobs:

  build:
    name: deploy to vm
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VMHOST }}
        username: ${{ secrets.VMUSERNAME }}
        password: ${{ secrets.VMPASSWORD }}
        port: ${{ secrets.VMPORT }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          cd ${{ secrets.vmdirectory }}
          docker-compose down
          docker image rm -f bt66/web-example-golang:latest
          docker-compose up
